### PR TITLE
Fix Issue: #27 injectable custom printers

### PR DESCRIPTION
**Pull request by andreaTP**
This is completely back compatible, even if type parameter is not so nice...

### CODE REVIEW

**Comment by andreaTP** [comment]
Could you please give me a feedback on this?
I want to publish on public github my sbt plugin, but, I do not want to depend on a fork of this great lib! :-)

**Comment by eed3si9n** [comment]
Sorry for the delay. Basically I think the implicit thing is a wrong approach.

The Scala compiler code base is already written using [Cake pattern][1]. If you want to swap out the printer, you should extend the `TreePrinters` and then bake your own cake like I did with [`Forest`][2].
You can copy-paste the file except you substitute `TreePrinters` with your `CoolTreePrinter` or something. Hope it works out!

  [1]: http://jonasboner.com/2008/10/06/real-world-scala-dependency-injection-di/
  [2]: https://github.com/eed3si9n/treehugger/blob/v0.4.1/library/src/main/scala/treehugger/Forest.scala

**Comment by andreaTP** [comment]
This would not work in an easy way,
as per:
https://github.com/eed3si9n/treehugger/blob/v0.4.1/library/src/main/scala/treehugger/TreePrinters.scala#L11
because of that the only thing that I can do is to extend Forest itself, than I have to copy past and modify all the methods there, this is not nice.
I do not want to copy-paste TreePrinter code because I need "ad-hoc" customisations only in some point, than a "pluggable" system will cover much better the use case.

If you do not like the implicit approach, please, propose another way.

**Comment by eed3si9n** [comment]
ok. So we should change the `self: Forest` to something more reusable.

**Comment by andreaTP** [comment]
Not so easy...
this is a really weird thing:
https://github.com/eed3si9n/treehugger/blob/v0.4.1/library/src/main/scala/treehugger/TreePrinters.scala#L36
also types are nested, changing that will cause a major structural refactoring of hierarchy.

**Comment by eed3si9n** [comment]
The nested type is the hallmark of the cake pattern. Let me see if I can make a demo app with your change applied on top of the current `TreePrinter` imple.

**Pull request closed without merging**
