### PR TITLE
Change DogGen from JavaDoc style to ScalaDoc style

### PR DESCRIPTION
**Pull request by julianpeeters**
Solution for issue 30

### CODE REVIEW

**Comment by eed3si9n** [comment]
Thanks!

**Comment by julianpeeters** [comment]
No problem, thanks for the library and for letting me contribute! Although I see I let a hilarious typo slip through in the commit message. Since we're not generating dogs, I'm happy to redo the pull request if you find the error to be too egregious :P

**Comment by eed3si9n** [comment]
haha. I didn't notice the canine twist. I'm ok with it as is.

**Comment by julianpeeters** [comment]
OK good good :+1:

**Pull request merged**
